---
title: "My Growth as a Data Scientist"
format: html
editor: visual
---

Prior to this quarter, I did not know anything about data science and working with data of any kind through programming. Working with R and its various packages has given me a great introduction into the field of data science. More specifically, I have learned a great deal of knowledge through working with dplyr functions to manipulate data sets. Interpreting data was familiar to me but changing data was foreign, so joins, grouping, and summarizing were very informative for me starting off in data science. One artifact that in my portfolio that I feel shows my growth with data manipulation is using the **across()** function in **PE-1.** The code artifact was one of my first attempts at cleaning data for further interpretation and manipulation. In addition, the code stays efficient by using the across function which is an added bonus. The artifact also shows my R abilities only three weeks into the Spring quarter, where I knew nothing prior. Throughout the quarter, I have honed these data manipulation skills being able to combine them with other useful skills for working with data. In addition, these skills have been extremely useful to me not just in this course, but in my course working with SQL. I discovered that many of the topics covered in the course carry over to working with data in SQL, and with these two courses combined, I have gotten a strong foundation with working with data.
