---
title: "The Power of Efficiency"
format: html
editor: visual
---

Statistical efficiency is the combination of readability and storage management. When working with larger data sets, its very likely that calculations and manipulations to the data will be resource intensive. By utilizing functions that are designed with algorithms to save resources, the programs can become more stable and allow for further operations to the data if needed. It's possible that without using efficient functions and algorithms, data oriented programs can refuse to run or stop running in the middle of its execution. While modern computing allows for some leeway in how statistical programs are created, the amount of data produced can reduce the likelihood that a program will execute flawlessly. In addition to resource management, efficiency also represents how readable the code of statistical programs are. If the code is readable, then its easier to understand how the code works which makes it easier to utilize that piece of code in another project or even alter the code for some other purpose. Most of my efficiency that I encountered came from using some form of iteration. This was typically seen when using the across function or using one of the map functions. When we started R, I wondered why we never used loops to iterate when manipulating data. When I learned about the map functions I finally understood why. It is because most functions already do the loops for us so we don't need to use them. So when I need to use the map functions like in PE-3, I can repeatedly run code without needing to explicitly call a loop.
